language: node_js
node_js:
  - "6.10.0"
services: mongodb
env:
  - TEST_DIR=UserService/server
  - TEST_DIR=ApplicantService
  - TEST_DIR=ta-corrd-service
before_script:
  - sleep 15
script:
  - cd UserService/server && npm install -g nodemon && npm install && npm start& cd $TEST_DIR && npm install && npm test
