let Client = require('node-rest-client').Client;
let client = new Client();
let Config = require('../config');
let forEach = require('async-foreach');

//create 200 student accounts, make applications and rankings
let user_accounts = [];
for(var i=0;i<200;i++){
  user_accounts.push('testing' + i.toString());
};

let first_names = [ 'Sophia',
  'Jackson',
  'Emma',
  'Aiden',
  'Olivia',
  'Lucas',
  'Ava',
  'Liam',
  'Mia',
  'Noah',
  'Isabella',
  'Ethan',
  'Riley',
  'Mason',
  'Aria',
  'Caden',
  'Zoe',
  'Oliver',
  'Charlotte',
  'Elijah',
  'Lily',
  'Grayson',
  'Layla',
  'Jacob',
  'Amelia',
  'Michael',
  'Emily',
  'Benjamin',
  'Madelyn',
  'Carter',
  'Aubrey',
  'James',
  'Adalyn',
  'Jayden',
  'Madison',
  'Logan',
  'Chloe',
  'Alexander',
  'Harper',
  'Caleb',
  'Abigail',
  'Ryan',
  'Aaliyah',
  'Luke',
  'Avery',
  'Daniel',
  'Evelyn',
  'Jack',
  'Kaylee',
  'William',
  'Ella',
  'Owen',
  'Ellie',
  'Gabriel',
  'Scarlett',
  'Matthew',
  'Arianna',
  'Connor',
  'Hailey',
  'Jayce',
  'Nora',
  'Isaac',
  'Addison',
  'Sebastian',
  'Brooklyn',
  'Henry',
  'Hannah',
  'Muhammad',
  'Mila',
  'Cameron',
  'Leah',
  'Wyatt',
  'Elizabeth',
  'Dylan',
  'Sarah',
  'Nathan',
  'Eliana',
  'Nicholas',
  'Mackenzie',
  'Julian',
  'Peyton',
  'Eli',
  'Maria',
  'Levi',
  'Grace',
  'Isaiah',
  'Adeline',
  'Landon',
  'Elena',
  'David',
  'Anna',
  'Christian',
  'Victoria',
  'Andrew',
  'Camilla',
  'Brayden',
  'Lillian',
  'John',
  'Natalie',
  'Lincoln' ];

let last_names = [ 'Smith',
  'Johnson',
  'Williams',
  'Jones',
  'Brown',
  'Davis',
  'Miller',
  'Wilson',
  'Moore',
  'Taylor',
  'Anderson',
  'Thomas',
  'Jackson',
  'White',
  'Harris',
  'Martin',
  'Thompson',
  'Garcia',
  'Martinez',
  'Robinson',
  'Clark',
  'Rodriguez',
  'Lewis',
  'Lee',
  'Walker',
  'Hall',
  'Allen',
  'Young',
  'Hernandez',
  'King',
  'Wright',
  'Lopez',
  'Hill',
  'Scott',
  'Green',
  'Adams',
  'Baker',
  'Gonzalez',
  'Nelson',
  'Carter',
  'Mitchell',
  'Perez',
  'Roberts',
  'Turner',
  'Phillips',
  'Campbell',
  'Parker',
  'Evans',
  'Edwards',
  'Collins',
  'Stewart',
  'Sanchez',
  'Morris',
  'Rogers',
  'Reed',
  'Cook',
  'Morgan',
  'Bell',
  'Murphy',
  'Bailey',
  'Rivera',
  'Cooper',
  'Richardson',
  'Cox',
  'Howard',
  'Ward',
  'Torres',
  'Peterson',
  'Gray',
  'Ramirez',
  'James',
  'Watson',
  'Brooks',
  'Kelly',
  'Sanders',
  'Price',
  'Bennett',
  'Wood',
  'Barnes',
  'Ross',
  'Henderson',
  'Coleman',
  'Jenkins',
  'Perry',
  'Powell',
  'Long',
  'Patterson',
  'Hughes',
  'Flores',
  'Washington',
  'Butler',
  'Simmons',
  'Foster',
  'Gonzales',
  'Bryant',
  'Alexander',
  'Russell',
  'Griffin',
  'Diaz',
  'Hayes',
  'Myers',
  'Ford',
  'Hamilton',
  'Graham',
  'Sullivan',
  'Wallace',
  'Woods',
  'Cole',
  'West',
  'Jordan',
  'Owens',
  'Reynolds',
  'Fisher',
  'Ellis',
  'Harrison',
  'Gibson',
  'Mcdonald',
  'Cruz',
  'Marshall',
  'Ortiz',
  'Gomez',
  'Murray',
  'Freeman',
  'Wells',
  'Webb',
  'Simpson',
  'Stevens',
  'Tucker',
  'Porter',
  'Hunter',
  'Hicks',
  'Crawford',
  'Henry',
  'Boyd',
  'Mason',
  'Morales',
  'Kennedy',
  'Warren' ];


forEach(user_accounts, function(item, index, arr){
  let sign_up_args = {
    data:{
      user: item,
      password: 'test'
    },
    headers: {
      "Content-Type": "application/json"
    }
  }
  client.post('http://localhost:3002/students/sign-up', sign_up_args, function(data,res){
    let token = data.user.user_token;
    let user_id = data.user.user_id;
    //make an application
    let applicationBody = {
      user_id,
      student_number: Math.floor(Math.random() * 10000000000),
      first_name: first_names[Math.floor(Math.random() * first_names.length)],
      last_name: last_names[Math.floor(Math.random() * last_names.length)],
      phone_number: "555-555-5555",
      program: "Computer Science",
      email: item + "@mail.utoronto.ca",
      year_of_study: Math.floor(Math.random() * ((4-1)+1) + 1);
      department: "Computer Science",
      department_explain: "I want to be in computer science",
      student_status: "",
      course_taken: ["CSC148", "CSC165"]
    };
    let applicant_args = {
      data: applicationBody,
      headers: {
        "Content-Type": "application/json",
        "x-access-token": token
      }
    }
    client.post('http://localhost:3003/application', applicant_args, function(data,res){
      //make rankings

    });
  });
});


//sign up for all accounts and have their user tokens, then make an application, then make a ranking
